### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by wildernessfamily** [confuzeus/django-perfect-breadcrumbs#1]
Hi, I found your Django package for breadcrumbs. I really like how it's laid out and the simplicity. Can I add a feature request? I'm the middle of a large project. If I wasn't working on this project Id do a pull request and add it but don't have time at the moment. After the project, I'll be more than happy to do take a look on implementing this feature.

The feature that I'm looking to add it the ability to add a breadcrumb that has no link. It's just a category separator. 
For example:
```
Home > About > FAQ's
Home > About > Contact Us
```

Where `About` has no link. It's just acts as a separator. 

I've tried:
```
breadcrumbs = [
    {"name": "Home", "url": reverse_lazy("home:home")},
    {"name": "About"},
    {"name": "FAQ's", "active": True},
]
```
and
```
breadcrumbs = [
    {"name": "Home", "url": reverse_lazy("home:home")},
    {"name": "About", "url": reverse_lazy("#")},
    {"name": "FAQ's", "active": True},
]
```
But neither worked. Only thing that did work was create a dummy url that I could use.
Thank you,

**Comment by confuzeus** [comment]
Hi,

Thanks using the package. You can do it by setting `active` to `True` for the item that needs no link. In your case:

```python
breadcrumbs = [
    {"name": "Home", "url": reverse_lazy("home:home")},
    {"name": "About", "active": True},
    {"name": "FAQ's", "active": True},
]
```

\- Josh
